In [ ]:
# Basic Dataset Creation

➦
DATA Test_Data1;
INPUT ID Name$ Age;
DATALINES;
101 Robin 32
102 Rony 27
103 Ronn 18
;
RUN;



#  (If We need Space between Names) (Remember putting extra space before team)

➦
DATA WEIGHT_CLUB4;
INPUT IDNUMBER NAME:& $ TEAM$ STARTWEIGHT ENDWEIGHT;
LOSS = STARTWEIGHT - ENDWEIGHT;
DATALINES;
1023 Faizul SHAW  RED 189 165
1049 AMELIA SERRANO  YELLOW 145 124
1219 ALAN ANCE  RED 210 192 /* Step-5 */
1246 RAVI SINHA  YELLOW 194 177
1078 ASHLEY MCKNIGHT  RED 127 118
; /* Step-6 */
RUN;

# By default length is of 8 characters if we want to increase then: (remember to put before INPUT statement)

➦
DATA WEIGHT_CLUB4;
LENGTH NAME $ 20.;
INPUT IDNUMBER NAME:& $ TEAM$ STARTWEIGHT ENDWEIGHT;
LOSS = STARTWEIGHT - ENDWEIGHT;
DATALINES;
1023 Faizul SHAW  RED 189 165
1049 AMELIA SERRANO  YELLOW 145 124
1219 ALAN ANCE  RED 210 192 /* Step-5 */
1246 RAVI SINHA  YELLOW 194 177
1078 ASHLEY MCKNIGHT  RED 127 118
; /* Step-6 */
RUN;



# If we want multiple increment of  variable, each should be provided separately

➦
DATA REPORT_CARD;
LENGTH NAME $ 20.;
LENGTH SUBJECT1 $ 20.;
LENGTH SUBJECT2 $ 20.; 
LENGTH SUBJECT3 $ 20.;
INPUT ID NAME$ SUBJECT1$ SUBJECT2$ SUBJECT3$ MARKS;
DATALINES;
101 FAIZUL PHYSICS CHEMISTRY MATH 289
102 MEGAN PHYSICS CHEMISTRY MATH 274
103 ROBBIE PHYSICS CHEMISTRY MATH 257
;
RUN;


➦
DATA WEIGHT;
LENGTH NAME$ 10.;
INPUT IDNUMBER NAME:& $ TEAM $ STARTWEIGHT ENDWEIGHT;
DATALINES;
101 DAVID SHAW  RED 189 165
;
RUN;


➦
DATA WEIGHT_CLUB2;
INPUT IDNUMBER NAME:& $ TEAM$ STARTWEIGHT ENDWEIGHT;
LENGTH NAME $ 20.;
DATALINES;
1023 DAVID SHAW  RED 189 165
1049 AMELIA SERRANO  YELLOW 145 124
1219 ALAN ANCE  RED 210 192 /* Step-5 */
1246 RAVI SINHA  YELLOW 194 177
1078 ASHLEY MCKNIGHT  RED 127 118
; /* Step-6 */
RUN;


➦
DATA WEIGHT_CLUB2;
INPUT IDNUMBER NAME $20. TEAM $ STARTWEIGHT ENDWEIGHT;
LENGTH NAME $20.; /* Increase the length of the NAME variable to 20 characters */
DATALINES;
1023 DAVID SHAW  RED 189 165
1049 AMELIA SERRANO  YELLOW 145 124
1219 ALAN ANCE  RED 210 192 /* Step-5 */
1246 RAVI SINHA  YELLOW 194 177
1078 ASHLEY MCKNIGHT  RED 127 118
; /* Step-6 */
RUN;


➦
DATA WEIGHT_CLUB4;
LENGTH NAME $ 20.;
INPUT IDNUMBER NAME:& $ TEAM$ STARTWEIGHT ENDWEIGHT;
LOSS = STARTWEIGHT - ENDWEIGHT;
DATALINES;
1023 Faizul SHAW  RED 189 165
1049 AMELIA SERRANO  YELLOW 145 124
1219 ALAN ANCE  RED 210 192 /* Step-5 */
1246 RAVI SINHA  YELLOW 194 177
1078 ASHLEY MCKNIGHT  RED 127 118
; /* Step-6 */
RUN;



➦
DATA REPORT_CARD;
LENGTH NAME $ 20.;
LENGTH SUBJECT1 $ 20.;
/* LENGTH SUBJECT2 $ 20.; */
LENGTH SUBJECT3 $ 20.;
INPUT ID NAME$ SUBJECT1$ SUBJECT2$ SUBJECT3$ MARKS;
DATALINES;
101 FAIZUL PHYSICS CHEMISTRY MATH 289
102 MEGAN PHYSICS CHEMISTRY MATH 274
103 ROBBIE PHYSICS CHEMISTRY MATH 257
;
RUN;
PROC MEANS DATA=REPORT_CARD MEAN;
  VAR Marks;
RUN;



# Column input method  


➦
DATA WEIGHT_CLUB; /* Step-1 */
INPUT IDNUMBER 1-4 NAME $6-24 TEAM $ 25-31 STARTWEIGHT ENDWEIGHT; /* Step-2 */
LOSS = STARTWEIGHT - ENDWEIGHT; /* Step-3 */
DATALINES; /* Step-4 */
1023 DAVID_SHAW     	RED	189 165
1049 AMELIA_SERRANO 	YELLOW 145 124
1219 ALAN_NANCE     	RED	210 192 /* Step-5 */
1246 RAVI_SINHA     	YELLOW 194 177
1078 ASHLEY_MCKNIGHT	RED	127 118
; /* Step-6 */
RUN;
TITLE = "WEIGHT CLUB DATASET"
PROC MEANS DATA=WEIGHT_CLUB;
RUN;




# Creating Libraries in SAS Base Package  

➦
LIBNAME DAY1 'C:\Users\USR\OneDrive\Desktop\3-2 books\SAS Slides\SAS CODES';
DATA DAY1.TEST_DATA1;
INPUT ID NAME$ GENDER$;
DATALINES;
01 MARK MALE
02 SUSAS FEMALE
03 ROB MALE
;
RUN;





# Creating a new library in SAS Studio  

➦
(First create a library through option LIBRARIES->MYLIBRARIES->RIGHT CLICK ON MOUSE->NEW LIBRARY)
DATA TEST3.TEST_DATA1;
INPUT ID NAME$ GENDER$;
DATALINES;
01 MARK MALE
02 SUSAS FEMALE
03 ROB MALE
;
RUN;


➦
DATA TEST3.TEST_DATA2;
INPUT ID NAME$ GENDER$;
DATALINES;
01 MARKahsdkfhaksdfhkasf MALE
02 SUSAS FEMALE
03 ROB MALE
;
RUN;

# In this code, as name takes only 8 characters so we can increase it to whatever we want (Remember that the Length command should be on top of Input)



➦
DATA TEST3.TEST_DATA3;
LENGTH NAME$30;
INPUT ID NAME$ GENDER$;
DATALINES;
01 MARKLAJFLSKJFLAJAOLSKFDJLKDF MALE
02 SUSAS FEMALE
03 ROB MALE
;
RUN;






# Exploring different options 
# 1. dlm(delimiter)

➦
DATA STD_DATA;
INPUT STDID NAME$ DEPT$;
DATALINES;
101 FAIZUL STAT
102 ROBIN PHARM
103 MEGAN LAW
;
RUN;

# In the above code we didn't give any kind of delimiter because by default SAS takes SPACE(' ') delimiter.As our data is already separated by Space that's why we didn't put any additional dlm statement . 


➦
DATA STD_DATA;
INFILE DATALINES DLM=',';
INPUT STDID NAME$ DEPT$;
DATALINES;
101,FAIZUL,STAT
102,ROBIN,PHARM
103,MEGAN,LAW
;
RUN;

# As our data is separated by comma we pass dlm=','  

➦
DATA STD_DATA;
INFILE DATALINES DLM='#';
INPUT STDID NAME$ DEPT$;
DATALINES;
101#FAIZUL#STAT
102#ROBIN#PHARM
103#MEGAN#LAW
;
RUN;
# As our data is separated by hash tag we pass dlm='#'  


# 2. Missover (considers missing values and keeps it blank)

➦
DATA STD_DATA;
INFILE DATALINES MISSOVER;
INPUT STDID NAME$ DEPT$;
DATALINES;
101 FAIZUL STAT
102 ROBIN
103 MEGAN LAW
;
RUN;

# One major problem of missover statement is it efficiently works only when the last value is missing.If the data is missing on somewhere middle, missover doesn't work properly .

➦
DATA STD_DATA;
INFILE DATALINES TRUNCOVER;
INPUT STDID NAME$ DEPT$;
DATALINES;
101 FAIZUL STAT
ROBIN
103 MEGAN LAW
;

RUN;

# TRUNCOVER is an alternative of MISSOVER 


3. INFILE statement

DATA SAMPLE_DATASET;
INFILE "C:\Users\USR\OneDrive\Desktop\3-2 books\SAS Slides\SAS CODES\BodyTemperature.txt"
INPUT Gender$ Age HeartRate Temperature;
RUN;





# If the dataset in your system is separated by comma

➦
DATA SAMPLE_DATASET;
INFILE "C:\Users\USR\OneDrive\Desktop\3-2 books\SAS Slides\SAS CODES\BodyTemperature.txt" dlm=',';
INPUT Gender$ Age HeartRate Temperature;
RUN;


# If the dataset in your system is separated by tab

DATA SAMPLE_DATASET;
INFILE "C:\Users\USR\OneDrive\Desktop\3-2 books\SAS Slides\SAS CODES\BodyTemperature.txt" dlm='09'X;
INPUT Gender$ Age HeartRate Temperature;
RUN;


PROC FREQ

# This  code will show the frequency distribution of all variables in the dataset 

➦
DATA TEST3.BTEMP;
INFILE '/home/u63597808/Sep21_Faiz/SAS Practice/BodyTemperature.txt';
INPUT Gender$ Age HeartRate Temperature;
RUN;
PROC FREQ DATA=TEST3.BTEMP;
RUN;

# If we don't want the frequency distribution of all the variables instead of some specific variables

➦
PROC FREQ DATA=BTEMP;
TABLES Gender HeartRate; (/*Though Gender is categorical but we didn't put $ here*/ )
RUN;

# Let's say we want to get the frequencies in descending order

➦
PROC FREQ DATA = BTEMP ORDER=FREQ;
RUN;



# If we want to arrange in ascending order

➦
PROC FREQ DATA=BTEMP ORDER=DATA;
RUN;

# If we don't want the cumulative frequency

➦
PROC FREQ DATA=BTEMP;
TABLES Gender HeartRate Temperature/NOCUM;
RUN;

# Two way cross tables

➦
PROC FREQ DATA=BTEMP;
TABLES Gender*Temperature;
RUN;


# Chi Square test to check association

➦
PROC FREQ DATA=BTEMP;
TABLES Gender * Age/CHISQ;
RUN;

# If we just want the frequency in crosstab and don't want row percentage or column percentage

➦
PROC FREQ DATA=BTEMP;
TABLES Gender * Age/CHISQ NOROW NOCOL


# PROC MEANS (GIVE SUMMARY STATISTICS FOR ALL NUMERIC VARIABLES)

➦
DATA TEST3.CARS;
SET SASHELP.CARS;
RUN;
PROC MEANS DATA=TEST3.CARS;
RUN  ;

# If We want summary statistics of specific variables

➦
PROC MEANS DATA=TEST3.CARS;
VAR Weight Wheelbase;
RUN;


# If we want to split the data based on any specific variables

➦
PROC MEANS DATA=TEST3.CARS;
CLASS Make;
RUN;

# If we don't want all the measures of summary statistics and want only some selected ones

➦
PROC MEANS DATA=TEST3.CARS SUM MEAN MEDIAN;
RUN;

# If we want summary statistics but not for every categories of a variable

➦
PROC MEANS DATA=TEST3.CARS;
CLASS Make;
WHERE Make IN ("Audi","Chevrolet");
RUN;


# PROC CORR (calculates correlation between variables)

# Remember PROC CORR also gives summary statistics

➦
PROC CORR DATA=TEST3.CARS;
RUN;




# Correlation of specific variables

➦
PROC CORR DATA=TEST3.CARS;
VAR Weight Horsepower;
RUN;

# by statement give different tables for each categories where the class statement gives all the categories in one single table

# Splitted correlation 

➦
PROC CORR DATA=TEST3.CARS;
var Weight Horsepower;
by Make;
Run;


# The above correlations are Pearson correlation coefficient if i want different correlation measures like spearman,kendall,Hoeffding

➦
PROC CORR DATA=TEST3.CARS SPEARMAN HOEFFDING KENDALL;
RUN;


# CONDITIONAL STATEMENTS

➦
DATA CLASS;
SET SASHELP.CLASS;
WHERE Sex="M";
RUN;

# Multiple Conditions

➦
DATA CLASS;
SET SASHELP.CLASS;
WHERE Sex="M" AND Age>14;
RUN;


# Using ‘in’ operator

➦
DATA CLASS;
SET SASHELP.CLASS;
WHERE AGE IN (12,14,15);  (It is basically equivalent to OR operator)
RUN;


➦
DATA CLASS;
SET SASHELP.CLASS;
WHERE AGE NOT IN (12,14,15);  (It is basically equivalent to OR operator)
RUN;

# Students whose name starts with 'A' 

➦
DATA CLASS;
SET SASHELP.CLASS;
WHERE Name LIKE 'A%' ;
RUN;


# Students whose name is having 5 characters

➦
DATA CLASS;
SET SASHELP.CLASS;
WHERE Name LIKE '_____';
RUN;

# We can filter out data if they are missing

➦
DATA CLASS;
SET SASHELP.CLASS;
WHERE Name is missing;
RUN;

or,
DATA CLASS;
SET SASHELP.CLASS;
WHERE Name=' ';
RUN;

# If numeric data is missing

➦
DATA CLASS;
SET SASHELP.CLASS;
WHERE Age=.;
RUN;

# Where data is not missing

➦
DATA CLASS;
SET SASHELP.CLASS;
WHERE Name ~=' ';
RUN;

or 
DATA CLASS;
SET SASHELP.CLASS;
WHERE Age~=;
RUN;


# If statements

➦
DATA CLASS;
SET SASHELP.CLASS;
IF Sex="M";
RUN;


➦
DATA CLASS;
SET SASHELP.CLASS;
IF Sex="M" and Age>14;
RUN;





➦
DATA CLASS;
SET SASHELP.CLASS;
IF Sex="M" and Age>14 THEN DELETE;
RUN;


➦
DATA CLASS;
SET SASHELP.CLASS;
IF Sex="M" THEN GENDER="MALE";
ELSE IF SEX="F" THEN GENDER="FEMALE";
RUN;


# If we want to do multiple things based one only one condition

➦
DATA CLASS;
SET SASHELP.CLASS;
IF Sex="M" THEN DO;
GENDER="MALE";
ORDER=1;
RACE='WHITE';
RUN;
END;  

# (END IS USED TO END THE DO STATEMENT)


# Informat and Format

# IMPORTING DATA FROM EXCEL FILE

# (Remember in the SAS studio first we have to upload the dataset into SAS studio, it won’t work if we just give the path of the file in our system like we did in Base SAS)

➦
DATA OPENING_DATE;
LENGTH REGION$ 20;
INPUT REGION$ OPENING_DATE CLOSING_DATE CURRENCY DOLLAR24.2;
INFORMAT OPENING_DATE DATE9. CLOSING_DATE DATE9. CURRENCY DOLLAR24.2;
FORMAT OPENING_DATE WEEKDATE20. CLOSING_DATE DATE9.;
DATALINES;
CALIFORNIA 25DEC1999 21OCT2020 52210
NEWYORK 11JAN2005 07JUL2022 586543
;
RUN;



➦
DATA EMP;
INPUT EMPID SALARY BOD;
INFORMAT SALARY COMMA6. BOD DATE9.;
FORMAT SALARY DOLLAR7. BOD DATE9.;
DATALINES;
101 2125854 05DEC2000
RUN;


# PROC IMPORT (IMPORTING DATASET INTO SAS)

➦
PROC IMPORT DATAFILE="/home/u63597808/Sep21_Faiz/single.xls"
OUT=TEST_DATASET_XL
DBMS= XLS; (See we didn’t close the semicolon till here)
RUN; 


# If we want to replace a dataset with same name

➦
PROC IMPORT DATAFILE="/home/u63597808/Sep21_Faiz/file.xls"
OUT=TEST_DATASET_XL2
DBMS= XLS REPLACE;
RUN;


# The problem is in the above code data automatically takes the first row values as heading of the variable, we don’t want that

➦
PROC IMPORT DATAFILE="/home/u63597808/Sep21_Faiz/single.xls"
OUT=TEST_DATASET_XL2
DBMS= XLS;
GETNAMES=NO;
RUN;


# If we have multiple excel sheets

➦
PROC IMPORT DATAFILE="/home/u63597808/Sep21_Faiz/single.xls"
OUT=TEST_DATASET_XL2
DBMS= XLS;
SHEET=’SHEET_NAME’;
RUN;


# If we want some specific part of the excel dataset

➦
PROC IMPORT DATAFILE="/home/u63597808/Sep21_Faiz/single.xls"
OUT=TEST_DATASET_XL2
DBMS= XLS;
RANGE =”SHEET_NAME$B5:E16”;
RUN;


# If we want to start from a specific row

➦
PROC IMPORT DATAFILE="/home/u63597808/Sep21_Faiz/single.xls"
OUT=TEST_DATASET_XL2
DBMS= XLS;
DATAROW=9;  (So it will start from the 9th row till the end)
RUN;








# If we don’t want every variable of the dataset

➦
PROC IMPORT DATAFILE="/home/u63597808/Sep21_Faiz/single.xls"
OUT=TEST_DATASET_XL2  (KEEP=COL1,COL4,COL5,..)
DBMS= XLS;
RUN;




# Importing CSV files


➦
PROC IMPORT DATAFILE="/home/u63597808/Sep21_Faiz/single.csv"
OUT=TEST_DATASET_csv2
DBMS= csv;
RUN;


# Importing text files

➦
PROC IMPORT DATAFILE="/home/u63597808/Sep21_Faiz/single.txt"
OUT=TEST_DATASET_csv2
DBMS= tab;
RUN;